dataset_name: customers

data_source:
  type: csv
  path: data/customers.csv

expectations:

  - type: expect_column_to_not_be_null
    column: customer_id

  - type: expect_column_values_to_be_unique
    column: customer_id

  - type: expect_column_values_to_be_of_type
    column: age
    dtype: int

  - type: expect_column_values_to_be_in_set
    column: gender
    values:
      - Male
      - Female

  - type: expect_column_values_to_be_between
    column: age
    min_value: 18
    max_value: 100

  - type: expect_column_mean_to_be_between
    column: age
    min_value: 20
    max_value: 60

  - type: expect_table_row_count_to_be_between
    min_value: 1
    max_value: 1000